using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Invoice.App.Views
{
    public partial class AnalyseView : UserControl
    {
        public AnalyseView()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            pivotGridControl1.DataSource = new System.Collections.Generic.List<Invoice.App.ViewModels.InvoiceListViewModel>();
        }
    }
}
